config/routes.rb
Abredatos2011::Application.routes.draw do
  

  resources :sources do
    resources :comments
  end
  
  resources :screenshots

  resources :categories

  resources :apps do
    resources :comments
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "home/index"

  root :to => "apps#index"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Ábrete de datos</title> 
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <style>
  <%= yield :style %>
  </style>
  <meta name="language" content="es" />
  <meta name="Description" content="Listado de aplicaciones que usan datos públicos, así como fuentes de datos públicos. Te permite comentar y opinar de cada uno.">
  
  <script type="text/javascript" charset="utf-8" src="http://cdn.jquerytools.org/1.2.5/full/jquery.tools.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
</head>

<body <%= body_class %>>
  <div id="wrapper">
    <h1 id="logo"><a href="/" title="Inicio">Ábrete de datos</a></h1>
    <ul id="login">
      <% if current_user %>
      <li>Signed in as <%= current_user.email %>. Not you?</li>
      <li><%= link_to "Sign out", destroy_user_session_path %></li>
      <% else %>
      <li>Haz login</li>
      <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => "facebook" %></li>
      <li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_apps), :class => "google_apps" %></li>
      <% end %>
    </ul>
    
    <ul id="menu">
      <li><%= link_to_unless_current "Listado de aplicaciones", apps_path %></li>
      <li><%= link_to_unless_current "Listado de fuentes", sources_path %></li>
    </ul>
    
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <div class="push"></div>
    
  </div> <!-- #wrapper -->

  <div id="footer">
    <div class="center">
      <h4>Todas estas aplicaciones utilizan fuentes de datos públicas. Accede al <%= link_to "directorio de fuentes", sources_path %>.</h4>
      <ul>
        <li><a href="/quienes-somos.html" title="">Quienes somos</a></li>
        <li><%= link_to "Nueva aplicación", new_app_path %></li>
        <li><%= link_to "Nueva fuente de datos", new_source_path %></li>
        <li><a href="http://abredatos.es" title="">Abredatos</a></li>
      </ul>
    </div> <!-- .center -->
  </div> <!-- #footer -->

<script type="text/javascript" charset="utf-8">
  <%= yield :javascript %>
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23203997-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>